#!/bin/bash

minifab query -p '"readMarble","marble1"' -t ''
minifab query -p '"readMarble","marble5"' -t ''
minifab query -p '"readMarble","marble9"' -t ''
minifab query -p '"readMarble","marble11"' -t ''
minifab query -p '"readMarble","marble111"' -t ''
minifab query -p '"readMarble","marble100"' -t ''
minifab query -p '"readMarble","marble12"' -t ''
minifab query -p '"readMarble","marble15"' -t ''
minifab query -p '"readMarble","marble201"' -t ''
minifab query -p '"readMarble","marble21"' -t ''
minifab query -p '"readMarble","marble51"' -t ''
minifab query -p '"readMarble","marble121"' -t ''
minifab query -p '"readMarble","marble71"' -t ''
minifab query -p '"readMarble","marble601"' -t ''
minifab query -p '"readMarble","marble351"' -t ''
